apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: RAMAN_BACHKAROU
spec:
  replicas: 10
  template:
    metadata:
    spec:
      containers:
      - name: app1
        image: mclover45/firstimage
        env:
          - name: MSG
            value: App1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-svc
  labels:
    app: app1
spec:
  ports:
  - port: 80
  selector:
    app: app1
