apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-default
    spec:
      containers:
      - name: app-default
        image: mclover45/firstimage
        env:
          - name: MSG
            value: Default Page
        ports:
        - name: http
          containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: app-default-svc
  labels:
    app: app-default
spec:
  ports:
  - port: 80
  selector:
    app: app-default
