---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-hello
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: app-hello
    spec:
      containers:
      - name: app-hello
        image: mclover45/firstimage
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-hello-svc
  labels:
    app: app-hello
spec:
  ports:
  - port: 80
  selector:
    app: app-hello
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-hello
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: webapps.example
    http:
      paths:
      - backend:
          serviceName: app-hello-svc
          servicePort: 80
